### ISSUE TITLE
How do I add nodejs to this container?

### ISSUE THREAD

**Issue by psmith3** [jazzdd86/alpine-flask#7]
Can you give me some advice on how to add nodejs to this container? I tried adding node to the requirements.txt file and that installs, but I cannot get a node command to run. Seems to be a path issue.

**Comment by jazzdd86** [comment]
Please see the part "Installing additional packages in alpine" in the Readme file. You need to put a requirements_image.txt file into the app root folder with all desired packages you want to install at the container creation. If you want to install packages during runtime please use the "docker exec" command as used with all other containers.

**Comment by psmith3** [comment]
Yes, I did actually try adding node to the requirements.txt file, but it would not run properly and all I could determine was it was possibly a path issue. Maybe I need to add something other that node?

**Comment by jazzdd86** [comment]
Did you add it to the requirements.txt? It should be a separate file named requirements_image.txt. 
If you did this correctly, connect to the running docker container and try to run node via shell. You should then see, if there are any problems. I don't use node, so I am not able to help you any further, sorry.

**Comment by psmith3** [comment]
Ahh. I will give that a try. Thanks for the reply.
