### ISSUE TITLE
Volume use?

### ISSUE THREAD

**Issue by yoyomeng2** [jazzdd86/alpine-flask#9]
Am trying to give my dev co-workers a common base image for our python apps. Is that more or less your intent by using with `VOLUME [${APP_DIR}]` ?

**Comment by jazzdd86** [comment]
Hi, yeah right, you can mount any app dir into the container using this image, without the need to build a new image for each application.
So its fantastic for developing python apps. But I use it for production environments too, because of its simplicity.
